import type { Metadata } from "next";
import { Geist as GeistFont, Geist_Mono as GeistMonoFont } from "next/font/google";
import "./globals.css";

const geistSans = GeistFont({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = GeistMonoFont({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
